remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: NGELPRO
description: Lead Generation and Sales Optimization Services for Startups 
url: https://motibahar.github.io/nglpro_website
